package io.uranus.utility.bundle.core.utility.chrono.helper.element;

import lombok.Getter;

@Getter
public enum ExpressionUnit {
    AFGHANISTAN("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    ALBANIA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    ALGERIA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    ANDORRA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    ANGOLA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    ARGENTINA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    ARMENIA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    AUSTRALIA_SYDNEY("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    AUSTRALIA_PERTH("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    AUSTRIA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    AZERBAIJAN("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    BAHRAIN("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    BANGLADESH("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    BELARUS("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    BELGIUM("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    BELIZE("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    BENIN("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    BHUTAN("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    BOLIVIA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    BOSNIA_AND_HERZEGOVINA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    BOTSWANA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    BRAZIL("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    BRUNEI("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    BULGARIA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    BURKINA_FASO("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    BURUNDI("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    CAMBODIA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    CAMEROON("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    CANADA_EASTERN("yyyy-MM-dd", "HH:mm", "yyyy-MM-dd HH:mm"),
    CANADA_CENTRAL("yyyy-MM-dd", "HH:mm", "yyyy-MM-dd HH:mm"),
    CANADA_MOUNTAIN("yyyy-MM-dd", "HH:mm", "yyyy-MM-dd HH:mm"),
    CANADA_PACIFIC("yyyy-MM-dd", "HH:mm", "yyyy-MM-dd HH:mm"),
    CHAD("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    CHILE("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    CHINA("yyyy-MM-dd", "HH:mm", "yyyy-MM-dd HH:mm"),
    COLOMBIA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    COSTA_RICA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    CROATIA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    CUBA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    CYPRUS("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    CZECH_REPUBLIC("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    DENMARK("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    DJIBOUTI("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    DOMINICAN_REPUBLIC("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    ECUADOR("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    EGYPT("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    EL_SALVADOR("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    ESTONIA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    ETHIOPIA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    FIJI("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    FINLAND("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    FRANCE("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    GABON("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    GAMBIA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    GEORGIA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    GERMANY("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    GHANA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    GREECE("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    GREENLAND("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    GUATEMALA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    GUINEA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    GUINEA_BISSAU("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    GUYANA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    HAITI("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    HONDURAS("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    HONG_KONG("yyyy-MM-dd", "HH:mm", "yyyy-MM-dd HH:mm"),
    HUNGARY("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    ICELAND("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    INDIA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    INDONESIA_JAKARTA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    INDONESIA_BALI("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    IRAN("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    IRAQ("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    IRELAND("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    ISRAEL("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    ITALY("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    IVORY_COAST("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    JAMAICA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    JAPAN("yyyy-MM-dd", "HH:mm", "yyyy-MM-dd HH:mm"),
    JORDAN("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    KAZAKHSTAN("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    KENYA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    KIRIBATI("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    KUWAIT("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    KYRGYZSTAN("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    LAOS("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    LATVIA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    LEBANON("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    LESOTHO("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    LIBERIA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    LIBYA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    LIECHTENSTEIN("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    LITHUANIA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    LUXEMBOURG("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    MACAU("yyyy-MM-dd", "HH:mm", "yyyy-MM-dd HH:mm"),
    MADAGASCAR("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    MALAWI("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    MALAYSIA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    MALDIVES("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    MALI("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    MALTA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    MARSHALL_ISLANDS("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    MAURITANIA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    MAURITIUS("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    MEXICO_CITY("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    MICRONESIA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    MOLDOVA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    MONACO("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    MONGOLIA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    MONTENEGRO("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    MOROCCO("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    MOZAMBIQUE("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    MYANMAR("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    NAMIBIA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    NAURU("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    NEPAL("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    NETHERLANDS("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    NEW_ZEALAND("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    NICARAGUA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    NIGER("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    NIGERIA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    NORTH_KOREA("yyyy-MM-dd", "HH:mm", "yyyy-MM-dd HH:mm"),
    NORWAY("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    OMAN("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    PAKISTAN("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    PALAU("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    PALESTINE("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    PANAMA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    PAPUA_NEW_GUINEA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    PARAGUAY("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    PERU("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    PHILIPPINES("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    POLAND("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    PORTUGAL("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    QATAR("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    REPUBLIC_OF_KOREA("yyyy.MM.dd", "HH:mm", "yyyy.MM.dd HH:mm"),
    ROMANIA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    RUSSIA_MOSCOW("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    RWANDA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    SAINT_KITTS_AND_NEVIS("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    SAINT_LUCIA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    SAINT_VINCENT_AND_THE_GRENADINES("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    SAMOA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    SAN_MARINO("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    SAO_TOME_AND_PRINCIPE("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    SAUDI_ARABIA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    SENEGAL("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    SERBIA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    SEYCHELLES("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    SIERRA_LEONE("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    SINGAPORE("yyyy-MM-dd", "HH:mm", "yyyy-MM-dd HH:mm"),
    SLOVAKIA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    SLOVENIA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    SOLOMON_ISLANDS("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    SOMALIA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    SOUTH_AFRICA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    SOUTH_SUDAN("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    SPAIN("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    SRI_LANKA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    SUDAN("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    SURINAME("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    SWAZILAND("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    SWEDEN("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    SWITZERLAND("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    SYRIA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    TAIWAN("yyyy-MM-dd", "HH:mm", "yyyy-MM-dd HH:mm"),
    TAJIKISTAN("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    TANZANIA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    THAILAND("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    TIMOR_LESTE("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    TOGO("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    TONGA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    TRINIDAD_AND_TOBAGO("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    TUNISIA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    TURKEY("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    TURKMENISTAN("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    TUVALU("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    UGANDA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    UKRAINE("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    UNITED_ARAB_EMIRATES("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    UNITED_KINGDOM("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    UNITED_STATES_EASTERN("MM-dd-yyyy", "hh:mm a", "MM-dd-yyyy hh:mm a"),
    UNITED_STATES_CENTRAL("MM-dd-yyyy", "hh:mm a", "MM-dd-yyyy hh:mm a"),
    UNITED_STATES_MOUNTAIN("MM-dd-yyyy", "hh:mm a", "MM-dd-yyyy hh:mm a"),
    UNITED_STATES_PACIFIC("MM-dd-yyyy", "hh:mm a", "MM-dd-yyyy hh:mm a"),
    URUGUAY("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    UZBEKISTAN("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    VANUATU("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    VATICAN("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    VENEZUELA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    VIETNAM("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    YEMEN("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    ZAMBIA("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm"),
    ZIMBABWE("dd-MM-yyyy", "HH:mm", "dd-MM-yyyy HH:mm");

    private final String dateFormat;
    private final String timeFormat;
    private final String dateTimeFormat;

    ExpressionUnit(String dateFormat, String timeFormat, String dateTimeFormat) {
        this.dateFormat = dateFormat;
        this.timeFormat = timeFormat;
        this.dateTimeFormat = dateTimeFormat;
    }

    public static ExpressionUnit withNation(String name) {
        return valueOf(name);
    }
}
